---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
type: Opaque
data:
  github-token: ${GITHUB_TOKEN}
  telegram-token: ${TG_TOKEN}
  telegram-chatid: ${TG_CHAT_ID}
  jenkins-password: ${JENKINS_PASSWORD}