jenkins:
  systemMessage: "<div style='border-radius:10px; text-align: center; padding:20px; font-size:160%; background-color: tomato;'>Jenkins configured automatically by Jenkins Configuration as Code plugin</div><br>"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  numExecutors: 2
  labelString: "master"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        name: "admin"
        password: ${JENKINS_PASSWORD}
security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  scriptApproval:
    approvedSignatures:
    - "new groovy.json.JsonBuilder java.lang.Object"
    - "method groovy.json.JsonBuilder toPrettyString"

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "github-http"
          password: ${GITHUB_TOKEN}
          scope: GLOBAL
          username: "dum307307@gmail.com"
      - string:
          description: "jenkins-sa-token"
          id: "jenkins-sa-token"
          scope: GLOBAL
          secret: ${JENKINS_SA_TOKEN}
      - string:
          description: "telegram token"
          id: "TG_TOKEN"
          scope: GLOBAL
          secret: ${TG_TOKEN}
      - string:
          description: "telegram chat id"
          id: "TG_CHAT_ID"
          scope: GLOBAL
          secret: ${TG_CHAT_ID}

unclassified:
  location:
    url: ${JENKINS_URL}

jobs:
  - file: /var/jenkins_home/casc_configs/seedjob.groovy