---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
type: Opaque
data:
  github-token: Z2hwX2t6VTRSdzQ5T2NaQ0VKVjA0dzNTMXVWUlltN2diMzNiVVloeQo=
  telegram-token: NTI0ODMzMTAxOTpBQUgzZEJOM3d3V2JuZk9fMnV1Nl9ZU2dmUmxza3N5cjFGdwo=
  telegram-chatid: NDc4NDk1OTEw
  jenkins-password: MVFBWjJ3c3g=