# Default values for app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecret: github

image:
  repository: ghcr.io/dum307/
  app: 
    productcatalogue: productcatalogue
    shopfront: shopfront
    stockmanager: stockmanager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  productcatalogue:
    port: 8020
  shopfront:
    port: 8010
  stockmanager:
      port: 8030
    

ingress:
  className: nginx
  productcatalogue:
    path: /products
  shopfront:
    path: /
  stockmanager:
    path: /stocks

