---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  type: {{ .Values.service.type }}
  selector:
    app: productcatalogue
  ports:
  - port: {{ .Values.service.productcatalogue.port }}
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  selector:
    matchLabels:
      app: productcatalogue
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      containers:
      - name: productcatalogue
        image: "{{ .Values.image.repository }}productcatalogue:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.productcatalogue.port }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
