---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  type: {{ .Values.service.type }}
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: {{ .Values.service.shopfront.port }}
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
spec:
  selector:
    matchLabels:
      app: shopfront
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      containers:
      - name: shopfront
        image: "{{ .Values.image.repository }}shopfront:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.shopfront.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.shopfront.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 1
