---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: stockmanager
  ports:
  - protocol: TCP
    port: {{ .Values.service.stockmanager.port }}
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      containers:
      - name: stockmanager
        image: "{{ .Values.image.repository }}stockmanager:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.stockmanager.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.stockmanager.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 1
